version: '3.9'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: accountowner
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  accountownerapp:
    depends_on:
      db:
        condition: service_healthy
        # restart: true
    # depends_on:
    #   - db
    image: localhost:50000/codemazeblog/accountowner:build-${BUILD_NUMBER_ACCOUNTOWNER}

  integration:
    depends_on:
      - accountownerapp
    image: localhost:50000/codemazeblog/accountowner:test
    build:
      context: .
      dockerfile: Dockerfile.Integration

volumes:
    dbdata: